" https://dougblack.io/words/a-good-vimrc.html

" set visuals
set termguicolors " enable gui color 
syntax enable " enable syntax processing
colorscheme one-monokai " https://github.com/fratajczak/one-monokai-vim

" change cursor modes for iTerm2
" 1 -> bar
" 2 -> underscore 
" 0 -> block
let &t_SI = "\<Esc>]50;CursorShape=1\x7" " INSERT mode
let &t_SR = "\<Esc>]50;CursorShape=2\x7" " REPLACE mode
let &t_EI = "\<Esc>]50;CursorShape=2\x7" " NORMAL mode (ELSE)

" 4 -> solid underscore
" 6 -> solid bar
autocmd VimLeave * silent !echo -ne "\033[6 q"
autocmd VimEnter * silent !echo -ne "\033[4 q"

" remove lag for cursor
set ttimeout
set ttimeoutlen=1
set ttyfast

set expandtab " tabs are spaces
set number " show line numbers
set relativenumber " show relative line numbers
set smartindent
" set tabstop=4 " number of visual spaces per TAB
" set softtabstop=4 " number of spaces in TAB when editing
" set showcmd " show command in bottom bar
" set cursorline " highlight current line
" set wildmenu " visual autocomplete for command menu
" set lazyredraw " redraw only when we need to
" set showmatch " highlight matching [{()}]

set incsearch " search as characters are entered
set hlsearch " highlight matches 

" move vertically by visual line rather than line break
nnoremap j gj
nnoremap k gk

" move to beginning/end of line
" cmd-h mapped to ^ in iTerm
" cmd-l mapped to $ in iTerm

" highlight last inserted text
" nnoremap gV `[v`]

let mapleader=","

" mapped esc to caps lock
set backspace=indent,eol,start " set backspace key
set visualbell " remove the beeping

call plug#begin()
" vim-plug: https://github.com/junegunn/vim-plug
" Default plugin directory is '~/.vim/plugged'
" Run :PlugInstall to install plugins

" vimtex configuration
Plug 'lervag/vimtex', { 'tag': 'v2.15' } 
filetype plugin indent on " necessary for vimtex
let g:tex_flavor='latex' 
let g:vimtex_view_method = 'zathura' " viewer method
let g:vimtex_compiler_method = 'latexmk' " default compiler backend
set conceallevel=1 " makes latex code invisible when your cursor not on line 
let g:tex_conceal='abdmg' " configure concealment
hi! clear Conceal " manually specifies highlight group for conceal characters

Plug 'sirver/ultisnips'
let g:UltiSnipsSnippetDirectories = ['~/.vim/UltiSnips/']
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

call plug#end()
